services:
  # Image from: https://hub.docker.com/_/mariadb
  db:
    # image: mariadb:10.8.2
    image: mariadb:${MARIADB:-10.6.7}
    # image: mariadb:10.7.3 
    # image: mariadb:10.6.7 
    restart: always
    volumes:
      - ./_db:/docker-entrypoint-initdb.d
      # - ./_log/mysql:/var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  db1067:
    image: mariadb:10.6.7 
    restart: always
    volumes:
      - ./_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  db1073:
    image: mariadb:10.7.3 
    restart: always
    volumes:
      - ./_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  db1082:
    image: mariadb:10.8.2-rc
    restart: always
    volumes:
      - ./_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress



  test:
    image: mariadb:${MARIADB:-10.6.7}
    profiles: ["utility"]
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: wordpress
    command: |
      bash -c  'for i in {1..10}
                do echo -e "⏳  \033[33mWaiting for MySQL server...\033[0m" &&
                  mysql -s -h db -e "exit" && break || sleep 3
                done &&
                sleep 1 &&
                echo -e "✔️   \033[32mConnected to MySQL\033[0m" &&
                mysql -h db $${MYSQL_DATABASE} -e "SELECT COUNT(*) FROM wp_postmeta" &&
                mysql -h db $${MYSQL_DATABASE} \
                      -e "SELECT SUBSTRING(meta_value,1,32) AS plaintext, SUBSTRING(HEX(meta_value), 1, 32) AS hex_encoded \
                          FROM wp_postmeta \
                          WHERE post_id = 1772 \
                          AND meta_key = \"additional_content\""'

  pass:
    image: mariadb:10.6.7
    profiles: ["utility"]
    depends_on:
      - db1067
    environment:
      MYSQL_DATABASE: wordpress
    command: |
      bash -c  'for i in {1..10}
                do echo -e "⏳  \033[33mWaiting for MySQL server...\033[0m" &&
                  mysql -s -h db1067 -e "exit" && break || sleep 3
                done &&
                sleep 1 &&
                echo -e "✔️   \033[32mConnected to MySQL\033[0m" &&
                mysql -h db1067 $${MYSQL_DATABASE} -e "SHOW TABLES" && 
                mysql -h db1067 $${MYSQL_DATABASE} \
                      -e "SELECT COUNT(*) FROM wp_postmeta" &&
                mysql -h db1067 $${MYSQL_DATABASE} \
                      -e "SELECT SUBSTRING(meta_value,1,32) AS plaintext, SUBSTRING(HEX(meta_value), 1, 32) AS hex_encoded \
                          FROM wp_postmeta \
                          WHERE meta_id = 76000" &&
                mysql -h db1067 $${MYSQL_DATABASE} \
                      -e "SELECT SUBSTRING(meta_value,1,32) AS plaintext, SUBSTRING(HEX(meta_value), 1, 32) AS hex_encoded \
                          FROM wp_postmeta \
                          WHERE post_id = 1772 \
                          AND meta_key = \"additional_content\""'

  fail:
    image: mariadb:10.8.2-rc
    profiles: ["utility"]
    depends_on:
      - db1073
    environment:
      MYSQL_DATABASE: wordpress
    command: |
      bash -c  'for i in {1..10}
                do echo -e "⏳  \033[33mWaiting for MySQL server...\033[0m" &&
                  mysql -s -h db1073 -e "exit" && break || sleep 3
                done &&
                sleep 1 &&
                echo -e "✔️   \033[32mConnected to MySQL\033[0m" &&
                mysql -h db1073 $${MYSQL_DATABASE} -e "SHOW TABLES" && 
                mysql -h db1073 $${MYSQL_DATABASE} -e "SELECT COUNT(*) FROM wp_postmeta" &&
                mysql -h db1073 $${MYSQL_DATABASE} \
                      -e "SELECT SUBSTRING(meta_value,1,32) AS plaintext, SUBSTRING(HEX(meta_value), 1, 32) AS hex_encoded \
                          FROM wp_postmeta \
                          WHERE meta_id = 76000" &&
                mysql -h db1073 $${MYSQL_DATABASE} \
                      -e "SELECT SUBSTRING(meta_value,1,32) AS plaintext, SUBSTRING(HEX(meta_value), 1, 32) AS hex_encoded \
                          FROM wp_postmeta \
                          WHERE post_id = 1772 \
                          AND meta_key = \"additional_content\""'

  # Runs phpMyAdmin on port 8002
  # Image from: https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    image: phpmyadmin:5.1.3-apache
    profiles: ["utility"]
    ports:
      - "${npm_config_port:-8002}:80"
    depends_on:
      - db1073
    environment:
      PMA_USER: root
      PMA_PASSWORD: ~
      UPLOAD_LIMIT: 1G
    command: |
      bash -c  'echo &&
                echo -e  "🛠   \033[33mStarting phpMyAdmin at\033[0m \033[36mhttp://localhost:${npm_config_port:-8002}\033[0m" &&
                echo &&
                /docker-entrypoint.sh apache2-foreground'
